#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=$(git hash-object -t tree /dev/null)
fi

allownocommit=$(git config --type=bool hooks.allownocommit)

# Redirect output to stderr.
exec 1>&2

if [ "$allownocommit" != "true" ] &&
	test $(git diff --cached --name-only | xargs grep '@nocommit' | wc -l) != 0
then
	printf "$(tput setaf 1)error: Attempt to add a file with @nocommit pragma.\n"
	printf "error: If you know what you are doing you can disable this check using:\n"
	printf "    git config hooks.allownocommit true$(tput sgr0)\n"

	exit 1
fi

# If there are whitespace errors, print the offending file names and fail.
exec git diff-index --check --cached $against --
